{
  "swagger" : "2.0",
  "info" : {
    "description" : "基于node开发的RESTful api, 用于个人实践项目。",
    "version" : "0.0.4",
    "title" : "node-RESTful-API",
    "contact" : {
      "email" : "jweboy0630@gmail.com"
    }
  },
  "host" : "118.24.155.105",
  "basePath" : "/api",
  "tags" : [ {
    "name" : "User",
    "description" : "用户"
  }, {
    "name" : "Upload",
    "description" : "文件上传"
  } ],
  "schemes" : [ "http" ],
  "paths" : {
    "/user/signup" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "用户注册",
        "parameters" : [ {
          "in" : "body",
          "name" : "user",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/User"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "OK"
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    },
    "/user/signin" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "用户登录",
        "parameters" : [ {
          "in" : "body",
          "name" : "user",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/User"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    },
    "/upload" : {
      "post" : {
        "tags" : [ "Upload" ],
        "summary" : "文件上传",
        "consumes" : [ "multipart/form-data" ],
        "parameters" : [ {
          "name" : "upfile",
          "in" : "formData",
          "description" : "需要上传的文件",
          "required" : false,
          "type" : "file"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    },
    "/upload/list" : {
      "get" : {
        "tags" : [ "Upload" ],
        "summary" : "文件列表",
        "parameters" : [ {
          "name" : "page",
          "in" : "query",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "size",
          "in" : "query",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/uploadList"
              }
            }
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    },
    "/upload/{id}" : {
      "delete" : {
        "tags" : [ "Upload" ],
        "summary" : "文件删除",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "需要删除的文件id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    }
  },
  "definitions" : {
    "User" : {
      "required" : [ "password", "username" ],
      "properties" : {
        "username" : {
          "type" : "string"
        },
        "password" : {
          "type" : "string"
        }
      },
      "example" : {
        "password" : "password",
        "username" : "username"
      }
    },
    "uploadList" : {
      "type" : "object",
      "required" : [ "id", "name", "putTime" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid",
          "example" : "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "name" : {
          "type" : "string",
          "example" : "node.png"
        },
        "putTime" : {
          "type" : "number",
          "example" : 1.52351758176587E14
        }
      },
      "example" : {
        "putTime" : 1.52351758176587E14,
        "name" : "node.png",
        "id" : "d290f1ee-6c54-4b01-90e6-d701748f0851"
      }
    }
  }
}